server:
  port: 9002

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:9000
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
        - id: inventory
          uri: http://localhost:9001
          predicates:
            - Path=/inventory-service/**
          filters:
            - RewritePath=/inventory-service/(?<segment>.*), /$\{segment}
        - id: validation-3p-route
          uri: http://sales-mw.gp1.lge.com/
          predicates:
            - Path=/sales/lazada/callback
          filters:
            - ValidationFilter
        - id: white-ip-3p-route
          uri: http://sales-mw.gp1.lge.com/
          predicates:
            - Path=/sales/**
          filters:
            - IpWhitelistFilter

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /order-service/v3/api-docs/D2C
        name: D2C Order Service
      - url: /inventory-service/v3/api-docs/D2C
        name: D2C Inventory Service

